### PR TITLE
Update the OpenVPN configuration keyword list

### PR DESCRIPTION
**Pull request by storm49152**
I skimmed through the OpenVPN 2.4 reference (2.5 does not seem to exist at the time of writing), and updated the keyword list that I found. It Works For Me.

### CODE REVIEW

**Comment by idleberg** [comment]
Thanks a lot for the PR. I will try to go through the changes on the weekend, so please have a little more patience!

**Comment by storm49152** [comment]
Hi. Sure, take your time; I'm using the changes locally already.
Unfortunately, I didn't find a reference for OpenVPN 2.5. And in the meantime I found out that there also appears to be a deprecated keyword list (I wasn't focussed on that when I was looking for keywords in the 2.4 reference), so my work is probably incomplete in that regard.

**Comment by idleberg** [comment]
The OpenVPN documentation is terrible. Would you have a link handy for the documentation you used?

**Comment by storm49152** [comment]
Yes, I found it terrible as well. When I saw it, at first I shied away, but in the end took the time to go through the whole doc anyway. I used:

https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/

I'm sorry, AFAIK it's not getting any better than this. And I'm still not finding a 2.5 reference...

**Comment by storm49152** [comment]
Well, things changed, and there are now reference manuals for 2.5 and 2.6:

https://openvpn.net/community-resources/reference-manual-for-openvpn-2-5/
https://openvpn.net/community-resources/reference-manual-for-openvpn-2-6/

However, I'm unsure if the reading experience will be better from before...

**Comment by idleberg** [comment]
I've verified the keywords, but there's a merge conflict. Actually, I might add a build system to make this more maintainable.

**Comment by storm49152** [comment]
Yes, well, I created the PR for v0.2.3, and you touched the `keyword.language.openvpn` regex in the `openvpn.tmLanguage` file when bumping to v0.3.0, so... ;-)
I'm a basic Git user, not a Git expert, and am unsure how to proceed. Do you need me to do anything?

**Comment by 1ukastesar** [comment]
> Yes, well, I created the PR for v0.2.3, and you touched the `keyword.language.openvpn` regex in the `openvpn.tmLanguage` file when bumping to v0.3.0, so... ;-) I'm a basic Git user, not a Git expert, and am unsure how to proceed. Do you need me to do anything?

You have to resolve the conflicts yourself locally (it's the best practice when collaborating on OSS).

Your approach could look something like:
```
cd <repo-dir>
git remote add upstream git@github.com:idleberg/vscode-openvpn.git # Or HTTPS version if you use that instead
git fetch upstream
git checkout Update-OpenVPN-keywords
git rebase upstream/main
# Then you have to resolve the conflicts, contact me if you don't know where to start
git add syntaxes/openvpn.tmLanguage
git rebase --continue
git push --force # Or create new commit and push if you are not sure
```

**Comment by storm49152** [comment]
Thanks. Did that.

**Comment by idleberg** [comment]
Thanks guys, you are awesome!

**Pull request merged**
